#' Calculate the fit for a dose-response curve
#'
#' @param intmat Intensity matrix as generated by
#'               \code{MALDIquant::intensityMatrix()}
#'               with rownames as the respectiv concentrations of the spectra.
#' @param idx    Numeric vector of the mz indicies to perform the fit.
#' @param ...    Additional arguments passed to \code{nplr::nplr()}
#'
#' @return
#' @export
#' @importFrom nplr nplr convertToProp
#' @importFrom dplyr mutate arrange %>%
#' @importFrom tibble as_tibble
calculateCurveFit <- function(intmat, idx, ...) {
  if (length(rownames(intmat)) == 0) {
    stop("intmat must have concentrations as rownames!\n")
  }

  current_res <- vector("list", length = length(idx))
  names(current_res) <- colnames(intmat[, idx])
  for (j in 1:length(idx)) {
    cat("fitting", round(as.numeric(colnames(intmat)[j]), 3),
        paste0("(", j, "/", length(idx), ")\n"))
    df <- intmat[, idx[j]] %>%
      as_tibble() %>%
      mutate(conc = rownames(intmat)) %>%
      mutate(conc = as.numeric(conc)) %>%
      arrange(conc)
    concLog <- log10(df$conc)
    if (any(concLog == -Inf)) {
      concLog[which(concLog == -Inf)] <- (min(concLog[which(!concLog == -Inf)]) - 1)
    }
    df <- df %>%
      mutate(concLog = concLog)
    resp <- convertToProp(y = df$value)
    model <- tryCatch(expr = {
      suppressWarnings(
        nplr(x = concLog, y = resp, useLog = FALSE, npars = 4, silent = TRUE, ...)
      )
    }, error = function(cond) {
      cat("m/z ", round(as.numeric(colnames(intmat)[j]), 3),
          "failed. Re-trying with npar='all' setting")
      suppressWarnings(

        return(nplr(x = concLog, y = resp, useLog = FALSE, npars = "all", silent = TRUE, ...))
      )
    })

    current_res[[j]] <- list(
      model = model,
      df = df
    )

    res_list <- current_res
  }
  return(res_list)
}
