#' get mass shift for target mz
#'
#' @param peaksdf       data.frame with peaks information as generated by peaks2df()
#' @param tol           Numeric, tolerance around targetMz
#' @param targetMz      Numeric, target mass
#' @param tolppm        Logical, is the tolerance provided in ppm (TRUE) or Daltion (FALSE)
#' @param allowNoMatch  Logical, stop if targetMz is not fround in single spectrum?
#'                      If TRUE spectra without targetMz match will be excluded.
#'
#' @return             List with two entries:
#'                                       MzShift The mass shift for each spectrum
#'                                       specIdx The index of the spectra with a match for targetMz
#'
#' @importFrom dplyr %>% mutate filter group_by arrange pull
#' @export

getMzShift <- function(peaksdf, tol, targetMz, tolppm = TRUE, allowNoMatch = TRUE) {
  plot_Idx <- sort(unique(peaksdf$plotIdx))

  if (tolppm) {
    resdf <- peaksdf %>%
      mutate(match = ifelse(mz > targetMz - mz * (tol / 1e6) & mz < targetMz + mz * (tol / 1e6), TRUE, FALSE))
    f_resdf <- resdf %>%
      filter(match) %>%
      mutate(mz.diff = round(targetMz - mz, 4)) %>%
      group_by(plotIdx) %>%
      filter(abs(mz.diff) == min(abs(mz.diff))) %>%
      arrange(plotIdx)
  } else {
    resdf <- peaksdf %>%
      mutate(match = mz > targetMz - tol & mz < targetMz + tol)
    f_resdf <- resdf %>%
      filter(match) %>%
      mutate(mz.diff = round(targetMz - mz, 4)) %>%
      group_by(plotIdx) %>%
      filter(abs(mz.diff) == min(abs(mz.diff))) %>%
      arrange(plotIdx)
  }


  if (!all(plot_Idx %in% (f_resdf %>% pull(plotIdx)))) {
    if (!allowNoMatch) {
      stop("Could not find ", targetMz, " for all spectra! Consider adjusting tol.\n")
    }
    warning("Could not find ", targetMz, " in spectrum ", paste(which(!(plot_Idx %in% (f_resdf %>% pull(plotIdx)))), collapse = ", "), ".\n")
    specIdx <- sort(which(plot_Idx %in% (f_resdf %>% pull(plotIdx))))
  } else {
    specIdx <- plot_Idx
  }
  if (length(specIdx) < 1) {
    stop("Could not find targetMz in any spectrum! Consider adjusting tol.\n")
  }

  return(list(
    mzshift = pull(f_resdf, mz.diff),
    specIdx = specIdx
  ))
}
