#' Get normalization factors from peak data.frame
#'
#' @param peaksdf       data.frame with peaks information as generated by peaks2df()
#' @param targetMz      Numeric, target mass
#' @param tol           Numeric, tolerance around targetMz
#' @param tolppm        Logical, is the tolerance provided in ppm (TRUE) or Daltion (FALSE)
#' @param allowNoMatch  Logical, stop if targetMz is not fround in single spectrum?
#'                      If TRUE spectra without targetMz match will be excluded.
#'
#' @return              List with two entries:
#'                                       norm_factor The normalization factor for each spectrum
#'                                       specIdx     The index of the spectra with a match for targetMz
#'
#' @importFrom dplyr pull %>% filter arrange
#' @export
getNormFactors <- function(peaksdf, targetMz, tol, tolppm = TRUE, allowNoMatch = TRUE) {

  plot_Idx <- sort(unique(peaksdf$plotIdx))

  if(tolppm) {
    resdf <- peaksdf %>%
      mutate(match = ifelse(mz > targetMz - mz*(tol/1e6) & mz < targetMz + mz*(tol/1e6), TRUE, FALSE))
    f_resdf <- resdf %>%
      filter(match) %>%
      arrange(plotIdx)
  } else {
    resdf <- peaksdf %>%
      mutate(match = mz > targetMz - tol & mz < targetMz + tol)
    f_resdf <- resdf %>%
      filter(match) %>%
      arrange(plotIdx)
  }

  if(!all(plot_Idx %in% (f_resdf %>% pull(plotIdx)))){
    if(!allowNoMatch) {
      stop("Could not find ", targetMz, " for all spectra! Consider adjusting tol.\n")
    }
    warning("Could not find ", targetMz, " in spectrum ", paste(which(!(plot_Idx %in% (f_resdf %>% pull(plotIdx)))), collapse = ", "), ".\n")
    specIdx <- which(plot_Idx %in% (f_resdf %>% pull(plotIdx)))
  } else {
    specIdx <- plot_Idx
  }
  if(length(specIdx) < 1) {
    stop("Could not find targetMz in any spectrum! Consider adjusting tol.\n")
  }
  return(list(norm_factor = pull(f_resdf, int),
              specIdx = specIdx))
}
